---
apiVersion: v1
kind: Namespace
metadata:
  name: glucosync-core
  labels:
    app.kubernetes.io/part-of: glucosync
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: glucosync-data
  labels:
    app.kubernetes.io/part-of: glucosync
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: glucosync-services
  labels:
    app.kubernetes.io/part-of: glucosync
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: glucosync-cicd
  labels:
    app.kubernetes.io/part-of: glucosync
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: glucosync-monitoring
  labels:
    app.kubernetes.io/part-of: glucosync
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: glucosync-admin
  labels:
    app.kubernetes.io/part-of: glucosync
    environment: production
